name: di
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _py-xgboost-mutex=2.0
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - click=8.2.1
  - icu=73.1
  - imbalanced-learn=0.14.1
  - intel-openmp=2025.0.0
  - joblib=1.5.3
  - ld_impl_linux-64=2.44
  - libexpat=2.7.4
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libmpdec=4.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libxgboost=3.1.2
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - ncurses=6.5
  - nltk=3.9.2
  - numexpr=2.14.1
  - numpy=2.4.1
  - numpy-base=2.4.1
  - openssl=3.0.19
  - packaging=25.0
  - pandas=2.3.3
  - patsy=1.0.2
  - pip=26.0.1
  - pthread-stubs=0.3
  - py-xgboost=3.1.2
  - python=3.14.2
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.3
  - python_abi=3.14
  - pytz=2025.2
  - readline=8.3
  - regex=2025.11.3
  - scikit-learn=1.8.0
  - scipy=1.16.3
  - setuptools=80.10.2
  - six=1.17.0
  - sklearn-compat=0.1.5
  - sqlite=3.51.1
  - statsmodels=0.14.6
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - threadpoolctl=3.5.0
  - tk=8.6.15
  - tqdm=4.67.1
  - tzdata=2025c
  - wheel=0.46.3
  - xgboost=3.1.2
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - accelerate==1.12.0
      - anyio==4.12.1
      - certifi==2026.1.4
      - filelock==3.20.0
      - fsspec==2025.12.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.4.1
      - idna==3.11
      - jinja2==3.1.6
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.6.1
      - nvidia-cublas==13.0.0.19
      - nvidia-cuda-cupti==13.0.48
      - nvidia-cuda-nvrtc==13.0.48
      - nvidia-cuda-runtime==13.0.48
      - nvidia-cudnn-cu13==9.13.0.50
      - nvidia-cufft==12.0.0.15
      - nvidia-cufile==1.15.0.42
      - nvidia-curand==10.4.0.35
      - nvidia-cusolver==12.0.3.29
      - nvidia-cusparse==12.6.2.49
      - nvidia-cusparselt-cu13==0.8.0
      - nvidia-nccl-cu13==2.27.7
      - nvidia-nvjitlink==13.0.39
      - nvidia-nvshmem-cu13==3.3.24
      - nvidia-nvtx==13.0.39
      - pillow==12.0.0
      - psutil==7.2.2
      - pyyaml==6.0.3
      - safetensors==0.7.0
      - sentence-transformers==5.2.2
      - shellingham==1.5.4
      - sympy==1.14.0
      - tokenizers==0.22.2
      - torch==2.9.1+cu130
      - torchaudio==2.9.1+cu130
      - torchvision==0.24.1+cu130
      - transformers==5.1.0
      - triton==3.5.1
      - typer-slim==0.21.1
      - typing-extensions==4.15.0